import { getSupabaseAdminClient } from "../../config/supabase.js";
import { mediaPublicUrl } from "../../config/media-storage.js";
import { AppError } from "../../shared/app-error.js";
const SELECT="id, author, team_name, message_id, message_en, label, photo_storage_path, sort_order, status, created_at, updated_at";
const mapItem=item=>({id:item.id,author:item.author,teamName:item.team_name,messageId:item.message_id,messageEn:item.message_en,label:item.label,photoStoragePath:item.photo_storage_path,photoUrl:mediaPublicUrl(item.photo_storage_path),sortOrder:item.sort_order,status:item.status,createdAt:item.created_at,updatedAt:item.updated_at});
const row=(input,adminId)=>({author:input.author,team_name:input.teamName,message_id:input.messageId,message_en:input.messageEn||null,label:input.label||null,photo_storage_path:input.photoStoragePath||null,sort_order:input.sortOrder??0,status:input.status||"draft",...(adminId?{created_by:adminId}:{})});
export function buildSupportLeaderboard(items){const counts=new Map();for(const item of items){const team=item.teamName.trim().replace(/\s+/g," ").toUpperCase();counts.set(team,(counts.get(team)||0)+1)}return[...counts.entries()].map(([team,count])=>({team,count})).sort((a,b)=>b.count-a.count||a.team.localeCompare(b.team)).slice(0,3).map((item,index)=>({...item,rank:index+1}))}
export async function listSupport({includeUnpublished=false}={},client=getSupabaseAdminClient()){let query=client.from("support_messages").select(SELECT).order("sort_order").order("created_at");if(!includeUnpublished)query=query.eq("status","published");const{data,error}=await query;if(error)throw new AppError(502,"Support messages could not be loaded");return data.map(mapItem)}
export async function createSupport(input,adminId,client=getSupabaseAdminClient()){const{data,error}=await client.from("support_messages").insert(row(input,adminId)).select(SELECT).single();if(error)throw new AppError(422,"Support message could not be created");return mapItem(data)}
export async function updateSupport(id,input,client=getSupabaseAdminClient()){const{data,error}=await client.from("support_messages").update(row(input)).eq("id",id).select(SELECT).single();if(error||!data)throw new AppError(404,"Support message not found");return mapItem(data)}
export async function deleteSupport(id,client=getSupabaseAdminClient()){const{data,error}=await client.from("support_messages").delete().eq("id",id).select("id, photo_storage_path").single();if(error||!data)throw new AppError(404,"Support message not found");return{id:data.id,photoStoragePath:data.photo_storage_path}}
