import { getSupabaseAdminClient } from "../../config/supabase.js";
import { AppError } from "../../shared/app-error.js";
const SELECT="id, title_id, title_en, body_id, body_en, status, published_at, created_at, updated_at";
const mapItem=item=>({id:item.id,titleId:item.title_id,titleEn:item.title_en,bodyId:item.body_id,bodyEn:item.body_en,status:item.status,publishedAt:item.published_at,createdAt:item.created_at,updatedAt:item.updated_at});
const row=(input,adminId)=>({title_id:input.titleId,title_en:input.titleEn||null,body_id:input.bodyId,body_en:input.bodyEn||null,status:input.status||"draft",published_at:input.status==="published"?new Date().toISOString():null,...(adminId?{created_by:adminId}:{})});
export async function listAnnouncements({includeUnpublished=false}={},client=getSupabaseAdminClient()){let query=client.from("announcements").select(SELECT).order("published_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(!includeUnpublished)query=query.eq("status","published");const{data,error}=await query;if(error)throw new AppError(502,"Announcements could not be loaded");return data.map(mapItem)}
export async function createAnnouncement(input,adminId,client=getSupabaseAdminClient()){const{data,error}=await client.from("announcements").insert(row(input,adminId)).select(SELECT).single();if(error)throw new AppError(422,"Announcement could not be created");return mapItem(data)}
export async function updateAnnouncement(id,input,client=getSupabaseAdminClient()){const{data:existing,error:readError}=await client.from("announcements").select("published_at").eq("id",id).single();if(readError||!existing)throw new AppError(404,"Announcement not found");const update=row(input);if(input.status==="published"&&existing.published_at)update.published_at=existing.published_at;const{data,error}=await client.from("announcements").update(update).eq("id",id).select(SELECT).single();if(error||!data)throw new AppError(404,"Announcement not found");return mapItem(data)}
export async function deleteAnnouncement(id,client=getSupabaseAdminClient()){const{data,error}=await client.from("announcements").delete().eq("id",id).select("id").single();if(error||!data)throw new AppError(404,"Announcement not found");return{id:data.id}}
