import {API_BASE,adminRequest,clearAdminSession,requireAdmin} from './admin-auth.js';
const rowsHost=document.querySelector('#rows'),pairHost=document.querySelector('#pair-rows'),status=document.querySelector('#status'),pairStatus=document.querySelector('#pair-status');
const rankingFallback=[['CURING',10],['BANBURY',8],['EXT',7],['CUTT',6],['TAS',5],['RMH . TWH',4],['TUBE',3],['TBS',2],['ENG',1]];
const pairFallback=[['BANBURY','BANGUN','HENDI'],['EXT','RODI','DOLI'],['CUTT','KARIRI','SUPRIYADI'],['TAS','SUMEDI','IQBAL'],['RMH . TWH','SUKANDAR','INDRAYANA'],['TUBE','UJANG','DINDIN'],['TBS','MAHMUDI','ICHSAN'],['ENG','ARIS H','KASWOTO'],['PSS','ALAMUDIN','ARI M'],['CURING','LUCKY K','APEP'],['FINAL INSP','ROHMAT','MINAN'],['W/S','M AIYAR','YOYO S'],['INMEC','IKHSAN S.','ARIEF S.'],['TECH. QA','PROBINSA','WAWAN R.'],['SHE/KSP','SAMSUL H','YUYUN F']];
function setStatus(host,message,error=false){host.textContent=message;host.className=error?'error':''}
function addRanking(row={name:'',score:0}){const item=document.createElement('div');item.className='ranking-edit-row';item.innerHTML='<input class="name" readonly aria-label="Nama tim atau departemen"><input class="score" type="number" min="0" step="1" required aria-label="Skor">';item.querySelector('.name').value=row.name;item.querySelector('.score').value=row.score??row.points??0;rowsHost.append(item)}
function addPair(pair={id:null,teamName:'',anglerOne:'',anglerTwo:''}){const item=document.createElement('div');item.className='pair-edit-row';item.dataset.id=pair.id||'';item.innerHTML='<input class="team" maxlength="160" required aria-label="Nama tim atau departemen"><input class="angler-one" maxlength="160" required aria-label="Nama pemancing pertama"><input class="angler-two" maxlength="160" required aria-label="Nama pemancing kedua"><button type="button">Hapus</button>';item.querySelector('.team').value=pair.teamName;item.querySelector('.angler-one').value=pair.anglerOne;item.querySelector('.angler-two').value=pair.anglerTwo;item.querySelector('button').onclick=()=>item.remove();pairHost.append(item)}
const renderRanking=rows=>{rowsHost.innerHTML='';rows.forEach(addRanking)};const renderPairs=pairs=>{pairHost.innerHTML='';pairs.forEach(addPair)};
const collectRanking=()=>[...rowsHost.children].map(row=>({name:row.querySelector('.name').value.trim(),score:Number(row.querySelector('.score').value)}));const collectPairs=()=>[...pairHost.children].map(row=>({id:row.dataset.id||null,teamName:row.querySelector('.team').value.trim(),anglerOne:row.querySelector('.angler-one').value.trim(),anglerTwo:row.querySelector('.angler-two').value.trim()}));
async function load(){setStatus(status,'Memuat ranking…');setStatus(pairStatus,'Memuat pasangan…');const[rankPayload,pairPayload]=await Promise.all([fetch(`${API_BASE}/tournaments/fishing-bp-2026/standings`).then(r=>r.json()),fetch(`${API_BASE}/tournaments/fishing-bp-2026/pairs`).then(r=>r.json())]);const savedRanking=rankPayload.data?.[0]?.rows||[],pairs=pairPayload.data?.length?pairPayload.data:pairFallback.map(([teamName,anglerOne,anglerTwo])=>({teamName,anglerOne,anglerTwo}));const scores=new Map(savedRanking.map(row=>[row.name.toLowerCase(),row.points]));renderPairs(pairs);renderRanking(pairs.map(pair=>({name:pair.teamName,score:scores.get(pair.teamName.toLowerCase())??0})));setStatus(status,savedRanking.length?'Nama mengikuti Tim & Pemancing. Ubah skor saja.':'Semua tim dimuat dengan skor awal 0.');setStatus(pairStatus,pairPayload.data?.length?'Pasangan tersimpan dimuat.':'Data awal pasangan siap disimpan.')}
document.querySelector('#add-pair').onclick=()=>addPair();
document.querySelector('#save').onclick=async()=>{try{setStatus(status,'Menyimpan ranking…');const payload=await adminRequest('/admin/tournaments/fishing-bp-2026/ranking',{method:'PUT',body:JSON.stringify({rows:collectRanking()})});renderRanking(payload.data);setStatus(status,`Ranking tersimpan. Champion: ${payload.meta.winner.name}.`)}catch(error){setStatus(status,error.message,true)}};
document.querySelector('#save-pairs').onclick=async()=>{try{setStatus(pairStatus,'Menyimpan pasangan…');const payload=await adminRequest('/admin/tournaments/fishing-bp-2026/pairs',{method:'PUT',body:JSON.stringify({pairs:collectPairs()})});setStatus(pairStatus,`${payload.meta.total} tim dan pasangan berhasil disimpan. Nama skor sudah disinkronkan.`);await load()}catch(error){setStatus(pairStatus,error.message,true)}};
document.querySelector('#logout-button').onclick=()=>{clearAdminSession();location.replace('admin-login.html')};if(await requireAdmin())load().catch(error=>{setStatus(status,error.message,true);setStatus(pairStatus,error.message,true)});
