import{futsalEntries,futsalGroups,futsalSchedule,futsalScorers}from'./data/futsal-data.js';
const toggle=document.querySelector('.sports-menu-toggle');toggle?.addEventListener('click',()=>{const open=document.body.classList.toggle('sports-nav-open');toggle.setAttribute('aria-expanded',String(open))});
const standings=document.querySelector('#futsal-standings');if(standings)standings.innerHTML=futsalGroups.map(group=>`<article class="standing-card"><h2>${group.name}</h2>${group.teams.map((team,i)=>`<div><b>0${i+1}</b><strong>${team[0]}</strong><span>${team[1]}</span></div>`).join('')}</article>`).join('');
const schedule=document.querySelector('#futsal-schedule');if(schedule)schedule.innerHTML=futsalSchedule.map(m=>`<article class="match-row"><time>${m.time}</time><strong>${m.home}</strong><b>VS</b><strong>${m.away}</strong><small>${m.round}</small></article>`).join('');
const bracket=document.querySelector('#futsal-bracket');if(bracket){const entries=futsalEntries.map((m,i)=>`<div class="futsal-slot entry" style="--slot:${i}"><span>${m.seed}</span><strong>${m.name}</strong><b>${m.score}</b></div>`).join('');const rounds=[0,1,2,3].map(i=>`<div class="futsal-slot r2" style="--slot:${i}"><strong>${i?'—':'TEAM 01'}</strong><b>${i?'—':'2'}</b></div>`).join('')+[0,1].map(i=>`<div class="futsal-slot r3" style="--slot:${i}"><strong>—</strong><b>—</b></div>`).join('')+`<div class="futsal-slot r4"><strong>—</strong><b>—</b></div><div class="futsal-slot final"><strong>—</strong><b>—</b></div>`;bracket.innerHTML=entries+rounds;
 const match=(a,b)=>`<article class="mobile-match"><div><small>${a.seed}</small><strong>${a.name}</strong><b>${a.score}</b></div><span>VS</span><div><small>${b.seed}</small><strong>${b.name}</strong><b>${b.score}</b></div></article>`;
 const opening=Array.from({length:8},(_,i)=>match(futsalEntries[i*2],futsalEntries[i*2+1])).join('');
 const pending=(count,label)=>Array.from({length:count},(_,i)=>`<article class="mobile-match pending"><div><strong>${i===0&&label==='QUARTER FINAL'?'TEAM 01':'MENUNGGU HASIL'}</strong><b>—</b></div><span>VS</span><div><strong>MENUNGGU HASIL</strong><b>—</b></div></article>`).join('');
 document.querySelector('.bracket-scroll').insertAdjacentHTML('afterend',`<section class="mobile-bracket clean-bracket" aria-label="Bracket Futsal"><header><p>16 TEAMS &bull; SINGLE ELIMINATION</p><h2>TOURNAMENT BRACKET</h2></header><section class="bracket-stage"><h3>ROUND OF 16</h3>${opening}</section><section class="bracket-stage"><h3>QUARTER FINAL</h3>${pending(4,'QUARTER FINAL')}</section><section class="bracket-stage"><h3>SEMI FINAL</h3>${pending(2,'SEMI FINAL')}</section><section class="bracket-stage"><h3>FINAL</h3>${pending(1,'FINAL')}</section><section class="bracket-stage champion-stage"><h3>CHAMPION</h3><div class="mobile-champion pending"><small>WINNER</small><strong>MENUNGGU HASIL</strong></div></section></section>`)
}
const scorers=document.querySelector('#futsal-scorers');if(scorers)scorers.innerHTML=futsalScorers.map((s,i)=>`<article><b>${i+1}</b><strong>${s[0]}</strong><span>${s[1]}</span></article>`).join('');
